load("@protobuf//bazel:proto_library.bzl", "proto_library")

proto_library(
    name = "stateswitchservice",
    srcs = ["stateswitchservice.proto"],
    visibility = ["//visibility:public"],
    deps = [
            "@protobuf//:empty_proto",
            "@protobuf//:timestamp_proto",
           ]
)
